import type { LanguageModel } from 'ai';
import type { MultiDocumentKBPort, MultiDocSearchResult } from '../ports/multi-doc.port.js';
import type { GraphStorePort, Community } from '../ports/graph-store.port.js';

/** Investigation layer level */
export type LayerLevel = 1 | 2 | 3 | 4;

/** Budget mode */
export type BudgetMode = 'fast' | 'balanced' | 'thorough';

/** Budget limits per mode */
export const BUDGET_LIMITS: Record<BudgetMode, number> = {
  fast: 10,
  balanced: 30,
  thorough: 100,
};

/** Operation costs */
export const OP_COSTS = {
  community_summary: 0,
  bm25_search: 1,
  graph_query: 2,
  section_read: 3,
  deep_analysis: 10,
} as const;

/** A hypothesis generated by the detective */
export interface Hypothesis {
  id: string;
  description: string;
  confidence: number;
  evidence: string[];
  status: 'active' | 'confirmed' | 'abandoned';
}

/** Investigation result */
export interface InvestigationResult {
  answer: string;
  layer: LayerLevel;
  hypotheses: Hypothesis[];
  sources: InvestigationSource[];
  budgetUsed: number;
  budgetLimit: number;
  thinking: string;
}

/** Source citation */
export interface InvestigationSource {
  documentId: string;
  nodeId: string;
  excerpt: string;
  relevance: number;
}

/** Options for the detective */
export interface DetectiveOptions {
  budget?: BudgetMode;
  forceLayer?: LayerLevel;
  maxHypotheses?: number;
}

/** Port for the AI Detective */
export interface DetectivePort {
  investigate(
    query: string,
    options?: DetectiveOptions,
  ): Promise<InvestigationResult>;

  classifyLayer(query: string): Promise<LayerLevel>;
}
